sample_data:
  required: true
  validate: file
fast5_directory:
  required: false
  validate: directory
sequencing_summary:
  required_if: fast5_directory
  validate: file
run_id:
  required: false
artic_use_medaka:
  required: false
  validate: boolean
artic_medaka_model:
  required: false
artic_primers_scheme:
  required: false
artic_normalise:
  validate: integer
gisaid_template:
  required: false
  validate: file
gisaid_submission_enabled:
  required: false
  validate: boolean
publish_minimum_completion:
  required: false
  validate: integer
output_directory:
  required: false
  pathtype: directory