sample_data:
  required: true
  validate: file
fast5_directory:
  required_if_true: artic_use_nanopolish
  validate: directory
sequencing_summary:
  required_if_true: artic_use_nanopolish
  validate: file
run_id:
  required: false
artic_primer_scheme:
  required: false
artic_medaka_model:
  required: false
artic_use_nanopolish:
  required: false
  validate: boolean
artic_normalise:
  validate: integer
gisaid_template:
  required: false
  validate: file
gisaid_submission_enabled:
  required: false
  validate: boolean
publish_minimum_completion:
  required: false
  validate: integer
multiqc_config:
  required: false
  validate: file
output_directory:
  required: false