name: ARTIC nCoV-2019 to GitHub Container Registry

on:
  push:
    branches: [main]
    paths:
      - "containers/artic-ncov2019/*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}/artic-ncov2019

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Log into Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat ./containers/artic-ncov2019/env.yaml | grep -Po '(?<=artic=)[0-9.]+')"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./containers/artic-ncov2019/
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.getversion.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
