name: Nextclade to DockerHub

on:
  push:
    branches: [main]
    paths:
      - containers/nextclade/*
  workflow_dispatch:

env:
  IMAGE: catgumag/nextclade

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat ./containers/nextclade/VERSION)"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./containers/nextclade/
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.getversion.outputs.version }}
            ${{ env.IMAGE }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
